[project]
name = "rv-form-prefill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32,<3",
]


[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "ruff>=0.12.11",
    "types-requests>=2.32.4.20250809",
]

[tool.mypy]
mypy_path = "rv_form_prefill"

